openapi: 3.0.3
info:
  title: Banking Transactions API
  description: API para gestionar transacciones bancarias (depósitos, retiros y transferencias)
  version: 1.0.0
  contact:
    name: Banking System Team
    email: support@bankingsystem.com

servers:
  - url: http://localhost:8080
    description: Servidor de desarrollo

paths:
  /transactions/accounts/{accountId}/deposit:
    post:
      tags:
        - Transactions
      summary: Realizar depósito
      description: Realiza un depósito en la cuenta especificada
      operationId: deposit
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
          description: ID de la cuenta bancaria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmountRequest'
      responses:
        '200':
          description: Depósito realizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          description: Error en la operación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /transactions/accounts/{accountId}/withdrawal:
    post:
      tags:
        - Transactions
      summary: Realizar retiro
      description: Realiza un retiro de la cuenta especificada
      operationId: withdrawal
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
          description: ID de la cuenta bancaria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmountRequest'
      responses:
        '200':
          description: Retiro realizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          description: Error en la operación (fondos insuficientes, cuenta no encontrada, etc.)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /transactions/accounts/transfer:
    post:
      tags:
        - Transactions
      summary: Realizar transferencia
      description: Realiza una transferencia entre dos cuentas
      operationId: transfer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '200':
          description: Transferencia realizada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          description: Error en la transferencia
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /transactions/accounts/{accountId}:
    get:
      tags:
        - Transactions
      summary: Obtener historial de transacciones
      description: Obtiene el historial de transacciones de una cuenta específica
      operationId: getTransactionHistory
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
          description: ID de la cuenta bancaria
      responses:
        '200':
          description: Historial de transacciones obtenido exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionResponse'

  /transactions:
    get:
      tags:
        - Transactions
      summary: Obtener todas las transacciones
      description: Obtiene todas las transacciones del sistema
      operationId: getAllTransactions
      responses:
        '200':
          description: Lista completa de transacciones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionResponse'

components:
  schemas:
    AmountRequest:
      type: object
      required:
        - amount
      properties:
        amount:
          type: number
          format: double
          minimum: 0.01
          description: Monto de la operación
          example: 100.50
      description: Request para operaciones con monto (depósito/retiro)

    TransferRequest:
      type: object
      required:
        - sourceAccountId
        - destinationAccountId
        - amount
      properties:
        sourceAccountId:
          type: string
          description: ID de la cuenta origen
          example: "12345"
        destinationAccountId:
          type: string
          description: ID de la cuenta destino
          example: "67890"
        amount:
          type: number
          format: double
          minimum: 0.01
          description: Monto a transferir
          example: 250.75
      description: Request para transferencias entre cuentas

    TransactionResponse:
      type: object
      properties:
        id:
          type: string
          description: ID único de la transacción
          example: "648b7f123456789abcdef012"
        type:
          $ref: '#/components/schemas/TransactionType'
        amount:
          type: number
          format: double
          description: Monto de la transacción
          example: 100.50
        date:
          type: string
          format: date
          description: Fecha de la transacción
          example: "2025-09-06"
        sourceAccountId:
          type: string
          description: ID de la cuenta origen
          example: "12345"
        destinationAccountId:
          type: string
          description: ID de la cuenta destino (solo para transferencias)
          example: "67890"
          nullable: true
      description: Respuesta con información de la transacción

    TransactionType:
      type: string
      enum:
        - DEPOSIT
        - WITHDRAWAL
        - TRANSFER
      description: Tipo de transacción
      example: DEPOSIT

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: Momento del error
        status:
          type: integer
          description: Código de estado HTTP
          example: 400
        error:
          type: string
          description: Tipo de error
          example: "Bad Request"
        message:
          type: string
          description: Mensaje descriptivo del error
          example: "Operation failed: Account not found"
        path:
          type: string
          description: Endpoint donde ocurrió el error
          example: "/transactions/accounts/12345/deposit"
      description: Respuesta de error estándar

tags:
  - name: Transactions
    description: Operaciones relacionadas con transacciones bancarias
